name: ci-javaTestUnit-workflow

on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: ['17', '21']
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 and 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Build with Maven
        run: mvn clean compile test
