name: ci-javaTestUnit-workflow
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: ['21']
        #os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        os: [ 'ubuntu-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
      - run: java java Main
      - run: java java MainTest